### ISSUE TITLE
Unable to use with sofa/eloquence

### ISSUE THREAD

**Issue by gerardbalaoro** [tylernathanreed/laravel-relation-joins#1]
[Sofa/Eloquence](https://github.com/jarektkaczyk/eloquence) ports with its own QueryBuilder class that extends Laravel's. So calling `joinRelations` on a model that uses Eloquence throws:

```
ReflectionException: Given object is not an instance of the class this property was declared in
..\vendor\reedware\laravel-relation-joins\src\Concerns\ForwardsParentCalls.php:78
```

It was this method:
```php
public function assignAcquiredProperties($parent)
    {
        foreach ((new ReflectionClass($parent))->getProperties() as $property) {
 
            if($property->isStatic()) {
                continue;
            }
 
            $property->setAccessible(true);
 
            $property->setValue($parent, $property->getValue($this));
 
        }
 
        return $this;
  }
```

**Comment by tylernathanreed** [comment]
@GerardBalaoro 

Since this is a cross-over issue with another third-party package, I'm considering this an enhancement, rather than a bug.

Nevertheless, I'll take a stab at it the next chance I get, but feel free to submit your own PR.

**Comment by tylernathanreed** [comment]
@gerardbalaoro,

With the introduction of Mixins in Laravel 6.x (and that now being the minimum supported version), I was able to rebuild this package using Mixins, rather than having to override the default query builder and relations.

Since that was the core issue here, I believe we can call this resolved.
