### ISSUE TITLE
Add possibility to call joinRelation() inside joinRelation()

### ISSUE THREAD

**Issue by NeutronSelector** [tylernathanreed/laravel-relation-joins#11]
Hello, 

Thank you for this package which works very well

Unless I missed something, the solution for the scenario below is as follows.
```php
->joinRelation('beneficiaryPrestation.beneficiary', fn($query) => $query->where(['status' => 'active']))
->joinRelation('beneficiaryPrestation AS beneficiary_prestation_2.prestation.places.placeExercise', fn($query) => $query->where([
    ['prestations.slug', '=', $prestationSlug], ['prestations.year', '=', $date->year],
    ['prestations.valid_from', '<=', $endOfMonth], ['prestations.valid_to', '>=', $startOfMonth], 
    ['places.valid_from', '<=', $endOfMonth], ['places.valid_to', '>=', $startOfMonth],
]))
```
Would it be possible to do something like this ?
```php
->joinRelation('beneficiaryPrestation', fn($query) => $query
    ->joinRelation('beneficiary', fn($query) => $query->where(['status' => 'active']))
    ->joinRelation('prestation.places.placeExercise', fn($query) => $query->where([
        ['prestations.slug', '=', $prestationSlug], ['prestations.year', '=', $date->year],
        ['prestations.valid_from', '<=', $endOfMonth], ['prestations.valid_to', '>=', $startOfMonth],
        ['places.valid_from', '<=', $endOfMonth], ['places.valid_to', '>=', $startOfMonth],
    ]))
)
OR
->joinRelation('beneficiaryPrestation', [
    // 'beneficiaryPrestation' => fn($query) => Some subquery if needed
    '.beneficiary' => fn($query) => $query->where(['status' => 'active']),
    '.prestation.places.placeExercise' => fn($query) => $query->where([
        ['prestations.slug', '=', $prestationSlug], ['prestations.year', '=', $date->year],
        ['prestations.valid_from', '<=', $endOfMonth], ['prestations.valid_to', '>=', $startOfMonth],
        ['places.valid_from', '<=', $endOfMonth], ['places.valid_to', '>=', $startOfMonth],
    ])
])
// The dot at first on nested relation is smart and nice for me, but i don't know if is tricky or no to achieve them
```
This makes it possible to avoid joining the same table twice when it is not necessary ?

Second point that could be interesting is to be able to trigger the virtual attributes of the joined models. Something like that ?
```php
->joinRelation('beneficiary', fn($query) => $query->withAppends(['virtual_field AS ben_virtual_field']))
```
And that for get all virttual attributs of beneficiary model (method without params)
```php
->joinRelation('beneficiary', fn($query) => $query->withAppends())
```
Another better possibility to do this would be to automatically trigger virtuls attributes of joined models and add a method to alias them
```php
->joinRelation('beneficiary', fn($query) => $query->appends(['virtual_field AS ben_virtual_field']))
```

I think these can be very useful additions.

**Comment by tylernathanreed** [comment]
When dealing with nested joins like this:

```php
$query->joinRelation('one', /* ... */);
$query->joinRelation('one.two', /* ... */);
$query->joinRelation('one.two.three', /* ... */);
```

This package already offers two solutions:

**1)** Through-Syntax
```php
$query->joinRelation('one', function ($join) { /* ... */ });
$query->joinThroughRelation('one.two', function ($join) { /* ... */ });
$query->joinThroughRelation('one.two.three', function ($join) { /* ... */ });
```

**2)** Array-Syntax
```php
$query->joinRelation('one.two.three', [
    'one' => function ($join) { /* ... */ },
    'two' => function ($join) { /* ... */ },
    'three' => function ($join) { /* ... */ }
]);
```

Either of these approaches would solve your nested join problem.

As for appends, I assume you're referring to [Appending Values to JSON](https://laravel.com/docs/8.x/eloquent-serialization#appending-at-run-time). These appends don't have any relation to eloquent queries, so I'm not certain how you intend to leverage this.

**Comment by NeutronSelector** [comment]
Thank you for your response and sorry for the delay in responding. I'm back from vacation

For nested join, my case is not that
```php
$query->joinRelation('one.two.three', /* ... */);
```
but
```php
$query->joinRelation('one.two_1', /* ... */)->joinRelation('one.two_2', /* ... */);
```
In this case, if y not aliasing "one as one_1" in second call joinRelation i get SQL Error : "Syntax error or access violation: 1066 Not unique table/alias".

For appends fields 
With laravel, if you add this in your model
```php
protected $appends = ['age'];

public function getAgeAttribute(): int
{
    return Carbon::createFromDate($this->getAttribute('birth_date'))->diffInYears(Carbon::now());
}
```
When call get() method on eloquent query, you get a property "appends" in model object. If you call get()->toArray(), eloquent auomaticly merge appends and attributes in on array. And by default, eloquent make this recursively in nested relations. 

In the case of joinRelation
```php
$query->joinRelation('one.two', /* ... */)->get()->toArray();
```
only appends of "one" are triggered and not of "two".

The behavior is therefore not the same as that of eloquent with nested relations.

**Comment by NeutronSelector** [comment]
I have found another solution.
Thanks
