### ISSUE TITLE
Global scope and ambiguous column names

### ISSUE THREAD

**Issue by konrad-ch** [tylernathanreed/laravel-relation-joins#18]
Hi, let me start by saying the library is great, very useful! :)

I have a problem with global scopes and tables with same column names.
For example:

**Product.php**
```class Product extends Model
{
    public function images()
    {
        return $this->hasMany(ProductImage::class, 'product_id', 'id');
    }

    protected static function booted()
    {
        static::addGlobalScope('active', function (Builder $builder) {
            $builder->where('status', '=', 1);
        });
    }
}
```

**ProductImage.php**
`model of table with 'status' column`

**SomeController.php**
```class SomeController extends Controller
{
    public function testMethod()
    {
        Product::query()->joinRelation('images')->limit(5)->get();
    }
}
```

Running testMethod() will cause 'Column 'status' in on clause is ambiguous' error.

Is there any way to deal with this case or the library just doesn't support it yet? I tried aliasing table names but it did not help, final query ignores that :(

**Comment by jgersain** [comment]
Yoy can specify the table name, for example

```
protected static function booted()
    {
        static::addGlobalScope('active', function (Builder $builder) {
            $builder->where('table_name.status', '=', 1);
        });
    }
```

**Comment by tylernathanreed** [comment]
As already mentioned, you should be able to qualify the table name. However, to support aliasing, you should do it like so:
```
protected static function booted()
{
    static::addGlobalScope('active', function (Builder $query) {
        $query->where($query->qualifyColumn('status'), '=', 1);
    });
}
```
