### ISSUE TITLE
Laravel 10 Compatibility

### ISSUE THREAD

**Issue by dzandrey** [tylernathanreed/laravel-relation-joins#23]
Please change laravel/framework dependency for Laravel 10

**Comment by albertricart** [comment]
Package has been pretty useful, I hope it supports Laravel 10 soon!

**Comment by tylernathanreed** [comment]
Laravel 10.x support is finally here!

**Comment by albertricart** [comment]
> Laravel 10.x support is finally here!

Awesome🤩
