### ISSUE TITLE
Remove Closure type hint from $callback parameter in other methods

### ISSUE THREAD

**Issue by brunolopesr** [tylernathanreed/laravel-relation-joins#25]
As the README states, there is support for array syntax for relations.

This works:

```
User::query()->joinRelation('posts.comments', [
    'comments' => fn ($join) => $join->where('comments.title', 'like', '%looking for something%')
]);
```

But this won't work, throwing an error that callback should be a ?Closure parameter:

```
User::query()->leftJoinRelation('posts.comments', [
    'comments' => fn ($join) => $join->where('comments.title', 'like', '%looking for something%')
]);
```

Well, after looking at the code, it seems that the only problem is the Closure type hint for $callback parameter in other methods than `joinRelation`, as these methods are just "helpers", I could achieve the left join with array-syntax with this:

```
User::query()->joinRelation('posts.comments', [
    'comments' => fn ($join) => $join->where('comments.title', 'like', '%looking for something%')
], 'left');
```

I can make a PR if its needed.

**Comment by tylernathanreed** [comment]
@brunolopesr, I've pushed a patch release (v4.0.2) to drop the type hint.

However, I'd like to use union typing here (e.g. `Closure|array`), which isn't available in PHP 7.4 (the currently lowest supported version of this package).

Therefore, I'll also be publishing a new major release soon (v5.0.0) that drops PHP 7.4 and Laravel 8 (as L8 is end of life now), bringing the minimums up to PHP 8.0 and Laravel 9. I'm also adding static analysis tooling in v5.0.0 to prevent this sort of issue in the future.

Thank for you bringing this to my attention.
