### ISSUE TITLE
Support orderBy of relation

### ISSUE THREAD

**Issue by Tofandel** [tylernathanreed/laravel-relation-joins#26]
Example
```php
Chapter::query()->joinRelation('part', fn ($q) => $q->orderBy('position'))->orderBy('position');
```

Currently produces
```sql
select * from `chapters` inner join `parts` on `parts`.`id` = `chapters`.`part_id` order by `position` asc
```
It seems `orderBy` in subQueries are completely ignored

Expected
```sql
select * from `chapters` inner join `parts` on `parts`.`id` = `chapters`.`part_id` order by `parts`.`position`, `position` asc
```

**Comment by tylernathanreed** [comment]
That's because you can't order on a join clause. The "expected" SQL would really be this:

```sql
select *
from `chapters`
    inner join `parts`
        on `parts`.`id` = `chapters`.`part_id`
            order by `parts`.`position`
order by `position`
```

SQL doesn't support this concept, and if you add an `orderBy` clause to a native Laravel join, it will be ignored as well.

You should be applying `orderBy` clauses to the root query builder:

```php
Chapter::query()->joinRelation('part')->orderBy('part.position')->orderBy('position');
```

**Comment by Tofandel** [comment]
I know you can do this

```
Chapter::query()->joinRelation('part')->orderBy('parts.position')->orderBy('position');
```
But the orderBy is on the table name, not on the relation name, which is the pain point

This package already have both queries so it's not about SQL supporting it, it's just about the package adding the orderBy in the subquery to the main query
