### ISSUE TITLE
Incompatible method for Laravel 8

### ISSUE THREAD

**Issue by Blacksky13** [tylernathanreed/laravel-relation-joins#9]
Hello!

Declaration of Reedware\LaravelRelationJoins\Concerns\ForwardsRelationCalls::getRelationCountHash() should be compatible with Illuminate\Database\Eloquent\Relations\Relation::getRelationCountHash($incrementJoinCount = true)  at vendor/reedware/laravel-relation-joins/src/Relation.php:74

  "name": "laravel/framework",
  "version": "v8.31.0",

**Comment by ahfa92** [comment]
this error already patched in PR by hasan @tylernathanreed #8

**Comment by tylernathanreed** [comment]
The related PR has been merged.
